- hosts: all
  name: "Install and configure Ceph via cephadm"
  become: true
  become_user: root
  become_method: su
  gather_facts: true
  vars:
    cephadm_bootstrap_additional_parameters: "--skip-mon-network --initial-dashboard-user  cephadmin --initial-dashboard-password qayxsw21"
    cephadm_mon_count: 3
    cephadm_commands:
      #- "config set mon public_network 10.0.0.0/24"
      - "fs new gradientdev cephfs-metadata cephfs-data"
      - "orch apply mds gradientdev --placement 3"
      - "auth get-or-create client.gradient"
    cephadm_pools:
      - name: cephfs-data
        application: cephfs
        state: present
        size: 3
      - name: cephfs-metadata
        application: cephfs
        state: present
        size: 3
      - name: rbd-internal
        application: rbd
        state: present
        size: 3
  pre_tasks:
    - name: "Update apt cache"
      ansible.builtin.apt:
        update_cache: true
    - name: "Setup NTP"
      ansible.builtin.import_role:
        name: geerlingguy.ntp
    - name: "Debug - output"
      ansible.builtin.debug:
        msg: "DEBUG - mon_ip {{ hostvars[inventory_hostname].ansible_facts[cephadm_public_interface].ipv4.address }}"
    - name: "Add apt dependencies for Docker"
      ansible.builtin.package:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present
    - name: "Setup Keyring file"
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
    - name: "Add Docker GPG key"
      ansible.builtin.get_url:
        url: "https://download.docker.com/linux/debian/gpg"
        dest: "/etc/apt/keyrings/docker.asc"
        mode: '0644'
    - name: "Remove non docker installs"
      ansible.builtin.package:
        name:
          - docker.io
          - docker-doc
          - docker-compose
          - podman-docker
          - containerd
          - runc
        state: absent
    - name: "Add Docker Repo"
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian  {{ ansible_distribution_release }} stable"
        state: present
    - name: "Update apt cache - Docker"
      ansible.builtin.apt:
        update_cache: true
    - name: "Install Docker"
      ansible.builtin.package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
  roles:
    - role: stackhpc.cephadm.cephadm
    - role: stackhpc.cephadm.pools
    - role: stackhpc.cephadm.keys
    - role: stackhpc.cephadm.commands
    #- name: "Import role"
     # vars:
     #   cephadm_bootstrap_additional_parameters: "--skip-mon-network"
     # ansible.builtin.import_role:
     #   name: stackhpc.cephadm.cephadm
