# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Terraform.gitlab-ci.yml

include:
  - template: Terraform/Base.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Terraform/Base.gitlab-ci.yml

variables:
  TF_VAR_ansible_ssh_key: $SSH_PUB_KEY

tf_output:
  stage: build
  environment:
    name: $TF_STATE_NAME
    action: prepare
  resource_group: ${TF_STATE_NAME}
  script:
    - gitlab-terraform output
    - gitlab-terraform output -json > cicd_tf_state.json
  artifacts:
    public: false
    paths:
      - cicd_tf_state.json


ansible_inventory:
  image: "registry.hub.docker.com/cytopia/ansible:latest-tools"
  stage: build
  needs:
    - tf_output
  image: "registry.hub.docker.com/cytopia/ansible:latest-tools"
  script:
    - cat cicd_tf_state.json
